spring.application.name=FinanceApp
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_db
spring.datasource.username=finance_user
spring.datasource.password=securepassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect